const LOADING = 'LOADING'
const CREATE_USER = 'CREATE_USER'
const LOAD_USERS = 'LOAD_USERS'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const ERROR = 'ERROR'

export {LOADING, CREATE_USER, LOAD_USERS, LOGIN_SUCCESS, ERROR}
