const LOADING = 'LOADING'
const CREATE_USER = 'CREATE_USER'
const LOAD_USERS = 'LOAD_USERS'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const ERROR = 'ERROR'
const GET_USER_PROFILE = 'GET_USER_PROFILE'

export {LOADING, CREATE_USER, LOAD_USERS, LOGIN_SUCCESS, ERROR, GET_USER_PROFILE}
