name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and audit
      run: |
        cd api
        npm install
        npm run build --if-present
        npm audit fix
    - name: Login to Docker Registry
      run: |
        cd api
        docker login -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Start env
      run: |
        cd api
        docker-compose up -d
        docker ps -a
        docker start api_postgres_1
        docker start api_prisma_1
        prisma deploy
        npm test
      env:
        CI: true


