name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Node.js modules
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: build, make test-coverage
      run: |
        npm install
        npm audit fix
        make test-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Initialize Google Cloud SDK
    #   uses: zxyle/publish-gae-action@master
    #   with:
    #     service_account_email: ${{ secrets.GCP_SA_EMAIL }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}
    #     project_id: ${{ secrets.PROJECT_ID }}
    #     gae_variables: ${{ secrets.GAE_VARIABLES }}
    # - name: Publish app to Google App Engine
    #   run: |
    #     gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
    #     gcloud config set project ${{ secrets.PROJECT_ID }}
    #     gcloud -q app deploy app.yaml --promote
      env:
        CI: true

